# Generated by Django 6.0.4 on 2026-06-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imgae_card',
            new_name='image_card',
        ),
    ]
